<!-- Generated by figma2htmlv1.1.0 on 2025-11-03 11:24 -->
<script>import { onMount } from "svelte";
export let resolveImage;
onMount(() => {((containerId) => {
				if (!('querySelector' in document))
						return;
				const elementInView = (el) => {
						const bounds = el.getBoundingClientRect();
						return bounds.top < window.innerHeight && bounds.bottom > 0;
				};
				const updateImgSrc = (img) => {
						const src = img.getAttribute('data-src');
						if (src && img.getAttribute('src') != src)
								img.setAttribute('src', src);
				};
				const onIntersectionChange = (entries) => {
						const isIntersecting = entries.reduce((memo, entry) => memo || entry.isIntersecting, false);
						if (isIntersecting) {
								waiting = false;
								update();
						}
				};
				const selectChildren = (selector, parent) => parent ? Array.prototype.slice.call(parent.querySelectorAll(selector)) : [];
				// based on underscore.js
				const throttle = (func, wait) => {
						let timeout = null;
						let previous = 0;
						const run = () => {
								previous = Date.now();
								timeout = null;
								func();
						};
						return function () {
								const remaining = wait - (Date.now() - previous);
								if (remaining <= 0 || remaining > wait) {
										clearTimeout(timeout);
										run();
								}
								else if (!timeout) {
										timeout = setTimeout(run, remaining);
								}
						};
				};
				const update = () => {
						const frames = selectChildren(`.${nameSpace}artboard:where([data-min-width],[data-max-width])`, container);
						// set width to either the container width or the window width, whichever is smaller
						const width = Math.min(Math.round(container.offsetWidth), window.innerWidth);
						// Set frame visibility based on container width
						frames.forEach(function (el) {
								const minwidth = el.getAttribute('data-min-width');
								const maxwidth = el.getAttribute('data-max-width');
								if (+minwidth <= width && (+maxwidth >= width || maxwidth === null)) {
										if (!waiting)
												selectChildren(`.${nameSpace}f2h-img`, el).forEach(updateImgSrc);
										el.style.display = 'block';
								}
								else {
										el.style.display = 'none';
								}
						});
						// Initialize lazy loading on first call
						if (waiting && !observer) {
								if (elementInView(container)) {
										waiting = false;
										update();
								}
								else {
										observer = new IntersectionObserver(onIntersectionChange, {
												rootMargin: '400px 400px'
										});
										observer.observe(container);
								}
						}
				};
				const container = document.getElementById(containerId);
				const onResize = throttle(update, 200);
				const nameSpace = '';
				let waiting = !!window.IntersectionObserver;
				let observer;
				update();
				document.addEventListener('DOMContentLoaded', update);
				window.addEventListener('resize', onResize);
		})("testfile-box", {namespace: "", setup: window.setupInteractive || window.getComponent});})</script><div id="testfile-box" class="figma2html">


	<!-- Frame: 300px -->
	<div id="f2h-frame-300" class="f2h-frame frame artboard" data-aspect-ratio="0.777" data-max-width="539">
		<div class="spacer" style="padding: 0 0 0 0; min-width: 300px; max-width: 539px;"></div>
		<picture>
			<img id="img-f2h-frame-300" class="f2h-img" alt="test" data-src="{resolveImage('300px.png', 'assetGroups/img').replace('nzz-q-assets', 'nzz-q-assets2')}" src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw==" loading="lazy" draggable="false" decoding="async" width="300.00" height="null"/>
		</picture>
<div class="f2h-text undefined" style="top: 2.76%; left: 9.56%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
			<p class="f2h-text-0  note">First</p>
		</div>
<div class="f2h-text undefined" style="top: 2.76%; left: 34.56%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
			<p class="f2h-text-1  note">Second</p>
		</div>
<div class="f2h-text undefined" style="top: 2.76%; left: 59.56%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
			<p class="f2h-text-2  note">Third</p>
		</div>
<div class="f2h-text undefined" style="top: 4.15%; left: 3.56%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
			<p class="f2h-text-3  note">300px</p>
		</div>
<div class="f2h-text undefined" style="top: 45.85%; left: 36.33%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
			<p class="f2h-text-4  note">Jonas</p>
		</div>
	</div>



	<!-- Frame: 540px -->
	<div id="f2h-frame-540" class="f2h-frame frame artboard" data-aspect-ratio="1.399" data-min-width="540">
		<div class="spacer" style="padding: 0 0 0 0; min-width: 540px; max-width: none;"></div>
		<picture>
			<img id="img-f2h-frame-540" class="f2h-img" alt="test" data-src="{resolveImage('540px.png', 'assetGroups/img').replace('nzz-q-assets', 'nzz-q-assets2')}" src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw==" loading="lazy" draggable="false" decoding="async" width="540.00" height="null"/>
		</picture>
<div class="f2h-text undefined" style="top: 2.59%; left: 5.19%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
			<p class="f2h-text-0  note">First</p>
		</div>
<div class="f2h-text undefined" style="top: 2.59%; left: 19.07%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
			<p class="f2h-text-1  note">Second</p>
		</div>
<div class="f2h-text undefined" style="top: 2.59%; left: 32.96%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
			<p class="f2h-text-2  note">Third</p>
		</div>
<div class="f2h-text undefined" style="top: 2.85%; left: 1.85%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
			<p class="f2h-text-3  note">540px</p>
		</div>
<div class="f2h-text undefined" style="top: 45.85%; left: 46.67%; opacity: 1; width: auto; transform: translate(0%, 0%) rotate(0deg); transform-origin: left top; text-align: left;">
			<p class="f2h-text-4  note">Jonas</p>
		</div>
	</div>
</div><style>	#testfile-box {
		max-width: none;
		margin: 0 auto;
	}

	#testfile-box .f2h-frame {
		margin: 0 auto;
	}

	#testfile-box p, #testfile-box .body {
		margin: 0;
	}

	#testfile-box .f2h-img {
		width: 100% !important;
		top: 0;
	}

	#testfile-box .f2h-symbol {
		box-sizing: border-box;
	}

	#testfile-box :where(.frame, .f2h-text, .f2h-symbol) {
		position: absolute;
	}

	#testfile-box :where(.f2h-link, .f2h-img) {
		display: block;
	}



	#f2h-frame-300 { position: relative; overflow: hidden; display: none; }

	#f2h-frame-300 .f2h-text-0.note { font-family: nzz-sans-serif, GT America, sans-serif; font-style: normal; font-weight: 300; font-size: 14px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
	#f2h-frame-300 .f2h-text-1.note { font-family: nzz-sans-serif, GT America, sans-serif; font-style: normal; font-weight: 300; font-size: 14px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
	#f2h-frame-300 .f2h-text-2.note { font-family: nzz-sans-serif, GT America, sans-serif; font-style: normal; font-weight: 300; font-size: 14px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
	#f2h-frame-300 .f2h-text-3.note { font-family: nzz-sans-serif, GT America, sans-serif; font-style: normal; font-weight: 300; font-size: 14px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
	#f2h-frame-300 .f2h-text-4.note { font-family: nzz-sans-serif, GT America, sans-serif; font-style: normal; font-weight: 300; font-size: 14px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }

	#f2h-frame-540 { position: relative; overflow: hidden; display: none; }

	#f2h-frame-540 .f2h-text-0.note { font-family: nzz-sans-serif, GT America, sans-serif; font-style: normal; font-weight: 300; font-size: 14px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
	#f2h-frame-540 .f2h-text-1.note { font-family: nzz-sans-serif, GT America, sans-serif; font-style: normal; font-weight: 300; font-size: 14px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
	#f2h-frame-540 .f2h-text-2.note { font-family: nzz-sans-serif, GT America, sans-serif; font-style: normal; font-weight: 300; font-size: 14px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
	#f2h-frame-540 .f2h-text-3.note { font-family: nzz-sans-serif, GT America, sans-serif; font-style: normal; font-weight: 300; font-size: 14px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }
	#f2h-frame-540 .f2h-text-4.note { font-family: nzz-sans-serif, GT America, sans-serif; font-style: normal; font-weight: 300; font-size: 14px; text-decoration: none; text-transform: none; line-height: 16px; letter-spacing: 0px; color: rgba(0, 0, 0, 1); mix-blend-mode: normal; }</style>
<!-- End figma2htmlv1.1.0 generated content - 2025-11-03 11:24 -->
